"""empty message

Revision ID: ef0228200a84
Revises: 0a936c4a9d64
Create Date: 2019-10-26 14:19:52.151019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0228200a84'
down_revision = '0a936c4a9d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('redeemed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_invite_redeemed'), 'invite', ['redeemed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_redeemed'), table_name='invite')
    op.drop_table('invite')
    # ### end Alembic commands ###
